/* Fine Jewellery catalog — Bloom & Safar
   Bloom copy rewritten as editorial description; Safar retains spec-style copy pending its own pass.
   Images pending; cards use stone tone. */
window.FJ_DATA = {
  "collections": [
    {
      "id": "bloom",
      "name": "Bloom",
      "lede": "Cycles of life. Every person blooms differently.",
      "story": "Just as a flower is cultivated for its beauty, the effort it takes to get to that stage often goes unnoticed. From sowing the seed, to becoming a sapling and eventually blooming into a flower.\n\nDrawing a parallel to life: the day we achieve our goal, we take a moment to look back and appreciate the challenges, effort and patience it took to get there. Hence, Bloom.\n\nThe different gemstones represent that every person has a different way of blooming. Mint garnet for quiet strength, growth and harmony. Aquamarine for clarity, courage and calmness. Tanzanite for new beginnings, the rarity of life's special moments, and wisdom. Pink spinel for healing, rebirth and love.\n\nStones used: mint garnet, aquamarine, tanzanite and pink spinel. Set in white gold.",
      "tone": "#6a9e7a",
      "banner": "img/bloom-banner.webp",
      "meta": "Mint garnet · Aquamarine · Tanzanite · Pink spinel · White gold",
      "models": [
        "img/products/gd26-68-1.webp",
        "img/products/gd26-61-1.webp",
        "img/products/gd26-69-2.webp",
        "img/products/gd26-63-2.webp"
      ]
    },
    {
      "id": "safar",
      "name": "Safar",
      "lede": "A journey through time. Designed with Shantanu Garg.",
      "story": "The Safar collection is inspired by a journey through time where Indian architectural heritage and modern expression converge into a singular narrative.\n\nInfluenced by the geometry, symmetry and intricate ornamentation of temple and Mughal architecture, and developed in collaboration with Shantanu Garg, each piece transforms traditional motifs into fluid, contemporary forms, reinterpreting India's architectural vocabulary into a modern, wearable expression.\n\nStructured yet effortless, the designs are conceived to be versatile and transformable, adapting seamlessly to the wearer while retaining their architectural essence.\n\nSafar embodies movement not just in form, but in meaning, capturing the evolution of design across cultures, reimagined for the present.",
      "tone": "#c45a7a",
      "banner": "img/safar-banner.webp",
      "designer": "Shantanu Garg",
      "meta": "Designed with Shantanu Garg",
      "models": [
        "img/products/gd26-196-c-3.webp",
        "img/products/gd26-224-1.webp",
        "img/products/gd25-294-2.webp",
        "img/products/gd26-148-3.webp"
      ]
    },
    {
      "id": "tide",
      "name": "Tide",
      "lede": "The rhythm of the ocean — graceful, constant, and ever in motion.",
      "story": "The Tide collection echoes the natural rhythm of the ocean, graceful, continuous, and ever in motion. Each design is developed through flowing contours and measured curves, creating a visual rhythm that guides light smoothly across the surface of the jewellery.\n\nWith each tide repeatedly touching the shore and slowly gliding back, it represents persistence and adaptability, a force shaped by time and repetition. In this collection, the wave becomes a language of balance, where movement is held within structure. Through precise craftsmanship and refined detailing, the Tide collection captures motion in a form that is enduring and composed.",
      "tone": "#3a7ea8",
      "banner": "img/tide-banner.webp",
      "meta": "Flowing contours · rhythm of the wave"
    },
    {
      "id": "swirl",
      "name": "Swirl",
      "lede": "Fluid, playful, and intuitively balanced motion.",
      "story": "The swirl collection is inspired by the playful yet delicate turning of form in motion. Each piece is shaped through soft rotations and layered curves, recreating a sense of flow that feels natural. The design focuses on smooth transitions and balanced proportions, allowing the form to move seamlessly.\n\nThe swirl evolves, guiding the eye and the light in a continuous path. Interpreted through fine craftsmanship the collection expresses movement with subtlety in jewellery that feels timeless.",
      "tone": "#7d6fa8",
      "banner": "img/swirl-banner.webp",
      "meta": "Soft rotations · layered curves"
    }
  ],
  "types": [
    "Necklaces",
    "Pendants",
    "Earrings",
    "Rings",
    "Bracelets"
  ],
  "products": [
    {
      "id": "gd26-148",
      "sku": "GD26-148",
      "name": "Tanzanite and diamond cuff bracelet",
      "collection": "Safar",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Tanzanite",
      "shape": "Round",
      "stonePcs": 1,
      "stoneCt": 0.27,
      "diamondCt": 1.94,
      "netG": 11.768,
      "grossG": 12.21,
      "story": "Crafted in White gold, set with 0.27 carats of intense blue tanzanite paired with 1.94 carats of brilliant cut diamonds",
      "tone": "#3a5f9a",
      "images": [
        "img/products/gd26-148.webp",
        "img/products/gd26-148-1.webp",
        "img/products/gd26-148-2.webp",
        "img/products/gd26-148-3.webp"
      ],
      "hover": "img/products/gd26-148-3.webp"
    },
    {
      "id": "gd25-1103",
      "sku": "GD25-1103",
      "name": "Pink spinel and diamond cuff bracelet",
      "collection": "Safar",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 1,
      "stoneCt": 0.24,
      "diamondCt": 2.07,
      "netG": 11.748,
      "grossG": 12.21,
      "story": "Crafted in White gold, set with 0.24 carats of vivid pink spinel paired with 2.07 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-1103.webp",
        "img/products/gd25-1103-1.webp",
        "img/products/gd25-1103-2.webp"
      ],
      "hover": "img/products/gd25-1103-1.webp"
    },
    {
      "id": "gd26-196-c",
      "sku": "GD26-196 C",
      "name": "Pink spinel and diamond motif bracelet",
      "collection": "Safar",
      "type": "Bracelets",
      "metal": "White and Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 1,
      "stoneCt": 0.41,
      "diamondCt": 1.08,
      "netG": 6.582,
      "grossG": 6.88,
      "story": "Crafted in Rose gold, set with 0.41 carats of vivid pink spinel paired with 1.08 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-196-c.webp",
        "img/products/gd26-196-c-1.webp",
        "img/products/gd26-196-c-2.webp",
        "img/products/gd26-196-c-3.webp"
      ],
      "hover": "img/products/gd26-196-c-3.webp"
    },
    {
      "id": "gd26-197-c",
      "sku": "GD26-197 C",
      "name": "Dual motif pink spinel and diamond bracelet",
      "collection": "Safar",
      "type": "Bracelets",
      "metal": "White and Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel",
      "shape": "Hexagon",
      "stonePcs": 8,
      "stoneCt": 1.36,
      "diamondCt": 1.356,
      "netG": 12.957,
      "grossG": 13.5,
      "story": "Crafted in Rose gold, set with 1.36 carats of hexagon cut pink spinel paired with 1.35 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-197-c.webp",
        "img/products/gd26-197-c-1.webp",
        "img/products/gd26-197-c-2.webp"
      ],
      "hover": "img/products/gd26-197-c-1.webp"
    },
    {
      "id": "gd26-224",
      "sku": "GD26-224",
      "name": "Pink spinel and diamond multi motif bracelet",
      "collection": "Safar",
      "type": "Bracelets",
      "metal": "White and Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 5,
      "stoneCt": 0.5,
      "diamondCt": 2.18,
      "netG": 25.884,
      "grossG": 26.42,
      "story": "Crafted in Rose gold, set with 0.5 carats of pink spinel paired with 2.18 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-224.webp",
        "img/products/gd26-224-1.webp"
      ],
      "hover": "img/products/gd26-224-1.webp"
    },
    {
      "id": "gd26-275-a",
      "sku": "GD26-275 A",
      "name": "Pink spinel and diamond statement bracelet",
      "collection": "Safar",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Beads",
      "stonePcs": 21,
      "stoneCt": 20.1,
      "diamondCt": 10.3,
      "netG": 33.67,
      "grossG": 39.75,
      "story": "Crafted in Rose gold, set with 20.1 carats of custom bead cut pink spinel paired with 10.3 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-275-a.webp"
      ]
    },
    {
      "id": "gd25-294",
      "sku": "GD25-294",
      "name": "Mix metal pink spinel and diamond safar motif earring",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "18k Rose Gold",
      "metalCode": "G-18kt-R",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 2,
      "stoneCt": 0.72,
      "diamondCt": 2.68,
      "netG": 15.95,
      "grossG": 16.63,
      "story": "Crafted in 18k Rose and white gold, set with 0.72 carats of pink spinel paired with 2.68 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-294.webp",
        "img/products/gd25-294-1.webp",
        "img/products/gd25-294-2.webp"
      ],
      "hover": "img/products/gd25-294-2.webp"
    },
    {
      "id": "gd25-842",
      "sku": "GD25-842",
      "name": "Rose rhodolite and diamond danglers",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "18k Rose Gold",
      "metalCode": "G-18kt-R",
      "stone": "Rose Rhodolite",
      "shape": "Pears",
      "stonePcs": 2,
      "stoneCt": 4.77,
      "diamondCt": 1.62,
      "netG": 10.482,
      "grossG": 11.76,
      "story": "Crafted in 18k White gold, set with 4.77 carats of Pear shaped Rose Rhodolite paired with 1.62 carats of brilliant cut diamonds",
      "tone": "#9a3a6a",
      "images": [
        "img/products/gd25-842.webp",
        "img/products/gd25-842-1.webp",
        "img/products/gd25-842-2.webp"
      ],
      "hover": "img/products/gd25-842-2.webp"
    },
    {
      "id": "gd26-140",
      "sku": "GD26-140",
      "name": "Morganite and diamond danglers",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "18k Rose Gold",
      "metalCode": "G-18kt-R",
      "stone": "Morganite",
      "shape": "Oval",
      "stonePcs": 2,
      "stoneCt": 4.33,
      "diamondCt": 1.15,
      "netG": 6.464,
      "grossG": 7.56,
      "story": "Crafted in 18k White gold, set with 4.33 carats of Oval Morganite paired with 1.15 carats of brilliant cut diamonds",
      "tone": "#e8b4b8",
      "images": [
        "img/products/gd26-140.webp",
        "img/products/gd26-140-1.webp",
        "img/products/gd26-140-2.webp"
      ],
      "hover": "img/products/gd26-140-2.webp"
    },
    {
      "id": "gd26-146",
      "sku": "GD26-146",
      "name": "Pink spinel and diamond hoop",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "White and Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 52,
      "stoneCt": 1.52,
      "diamondCt": 0.7,
      "netG": 12.166,
      "grossG": 12.61,
      "story": "Crafted in White gold, set with 1.52 carats of vivid Pink spinel paired with 0.7 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-146.webp",
        "img/products/gd26-146-1.webp",
        "img/products/gd26-146-2.webp"
      ],
      "hover": "img/products/gd26-146-2.webp"
    },
    {
      "id": "gd26-147",
      "sku": "GD26-147",
      "name": "Tanzanite and diamond hoop",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Tanzanite",
      "shape": "Round",
      "stonePcs": 2,
      "stoneCt": 0.21,
      "diamondCt": 1.33,
      "netG": 11.762,
      "grossG": 12.07,
      "story": "Crafted in White gold, set with 1.21 carats of vivid round tanzanite paired with 1.33 carats of brilliant cut diamonds",
      "tone": "#3a5f9a",
      "images": [
        "img/products/gd26-147.webp",
        "img/products/gd26-147-1.webp",
        "img/products/gd26-147-2.webp"
      ],
      "hover": "img/products/gd26-147-2.webp"
    },
    {
      "id": "gd26-197-b",
      "sku": "GD26-197 B",
      "name": "Pink spinel and diamond motif earring",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "White and Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel",
      "shape": "Hexagon",
      "stonePcs": 8,
      "stoneCt": 2.93,
      "diamondCt": 1.68,
      "netG": 10.148,
      "grossG": 11.07,
      "story": "Crafted in White gold, set with 2.93 carats of custom cut hexagon pink spinel paired with 1.68 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-197-b.webp",
        "img/products/gd26-197-b-1.webp",
        "img/products/gd26-197-b-2.webp"
      ],
      "hover": "img/products/gd26-197-b-2.webp"
    },
    {
      "id": "gd26-198-c",
      "sku": "GD26-198 C",
      "name": "Tourmaline, rose quartz and diamond motif earring",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14t-W",
      "stone": "Tourmaline & Rose Quartz",
      "shape": "Triangle",
      "stonePcs": 12,
      "stoneCt": 3.28,
      "diamondCt": 0.93,
      "netG": 12.264,
      "grossG": 19.08,
      "story": "Crafted in White gold, set with 3.28 carats of custom cut triangle tourmaline set in 29.87 carats of carved rose quartz paired with 0.93 carats of brilliant cut diamonds",
      "tone": "#2a7a5a",
      "images": [
        "img/products/gd26-198-c.webp"
      ]
    },
    {
      "id": "gd26-203",
      "sku": "GD26-203",
      "name": "Pink spinel, rose quartz and diamond motif earring",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Pink Spinel & Rose Quartz",
      "shape": "Pears",
      "stonePcs": 2,
      "stoneCt": 2.31,
      "diamondCt": 0.716,
      "netG": 11.341,
      "grossG": 14.99,
      "story": "Crafted in 18k White gold, set with 2.31 carats of pear shape pink spinel set in 15.22 carats of carved rose quartz paired with 0.71 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-203.webp"
      ]
    },
    {
      "id": "gd26-218",
      "sku": "GD26-218",
      "name": "Pink spinel and diamond sleek dangler",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "Rose Gold",
      "metalCode": "G-14kt-R",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 2,
      "stoneCt": 0.56,
      "diamondCt": 1.22,
      "netG": 8.444,
      "grossG": 8.8,
      "story": "Crafted in Rose gold, set with 0.56 carats of vivid round pink spinel paired with 1.22 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-218.webp",
        "img/products/gd26-218-1.webp",
        "img/products/gd26-218-2.webp"
      ],
      "hover": "img/products/gd26-218-2.webp"
    },
    {
      "id": "gd26-275-b",
      "sku": "GD26-275 B",
      "name": "Pink spinel and diamond motif stud",
      "collection": "Safar",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Beads",
      "stonePcs": 2,
      "stoneCt": 3.54,
      "diamondCt": 1.73,
      "netG": 6.044,
      "grossG": 7.1,
      "story": "Crafted in White gold, set with 3.54 carats of custom bead cut pink spinel paired with 1.73 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-275-b.webp"
      ]
    },
    {
      "id": "gd26-141",
      "sku": "GD26-141",
      "name": "Morganite and diamond pendant",
      "collection": "Safar",
      "type": "Pendants",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Morganite",
      "shape": "Oval",
      "stonePcs": 1,
      "stoneCt": 2.04,
      "diamondCt": 0.45,
      "netG": 2.552,
      "grossG": 3.05,
      "story": "Crafted in White gold, set with 2.04 carats of oval Morganite paired with 0.45 carats of brilliant cut diamonds",
      "tone": "#e8b4b8",
      "images": [
        "img/products/gd26-141.webp",
        "img/products/gd26-141-1.webp",
        "img/products/gd26-141-2.webp"
      ],
      "hover": "img/products/gd26-141-2.webp"
    },
    {
      "id": "gd26-197",
      "sku": "GD26-197",
      "name": "Pink spinel and diamond motif pendant",
      "collection": "Safar",
      "type": "Pendants",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Hexagon",
      "stonePcs": 4,
      "stoneCt": 1.66,
      "diamondCt": 0.796,
      "netG": 5.349,
      "grossG": 5.84,
      "story": "Crafted in White gold, set with 1.66 carats of custom cut hexagon pink spinel paired with 5.35 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-197.webp",
        "img/products/gd26-197-1.webp",
        "img/products/gd26-197-2.webp",
        "img/products/gd26-197-3.webp"
      ],
      "hover": "img/products/gd26-197-3.webp"
    },
    {
      "id": "gd26-275-c",
      "sku": "GD26-275 C",
      "name": "Pink spinel and diamond motif pendant",
      "collection": "Safar",
      "type": "Pendants",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Beads",
      "stonePcs": 1,
      "stoneCt": 1.78,
      "diamondCt": 1.37,
      "netG": 2.44,
      "grossG": 3.07,
      "story": "Crafted in White gold, set with 1.78 carats of custom bead cut pink spinel paired with 2.44 carats of brilliant cut diamonds",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-275-c.webp"
      ]
    },
    {
      "id": "gd25-1081",
      "sku": "GD25-1081",
      "name": "Mint garnet and diamond bloom pendant",
      "collection": "Bloom",
      "type": "Pendants",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 1.55,
      "diamondCt": 0.45,
      "netG": 1.76,
      "grossG": 2.16,
      "story": "Mint garnet speaks of quiet strength, the kind of growth no one applauds until it's finished. This pendant sets a 1.55 carat pear-cut stone, cool and green as new leaves, among 0.45 carats of brilliant-cut diamonds in white gold — small enough to wear every day, deliberate enough to mean something.",
      "tone": "#6a9e7a",
      "images": [
        "img/products/gd25-1081.webp"
      ]
    },
    {
      "id": "gd25-1069",
      "sku": "GD25-1069",
      "name": "Mint garnet and diamond bloom ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 2.47,
      "diamondCt": 1.1,
      "netG": 4.506,
      "grossG": 5.22,
      "story": "A bolder measure of the same idea: 2.47 carats of pear-cut mint garnet held by 1.1 carats of diamonds in white gold. Mint garnet is Bloom's stone for harmony, and on the hand it reads as a steady, grounded kind of glamour.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd25-1067",
      "sku": "GD25-1067",
      "name": "Mint garnet and diamond bloom earring",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 4.31,
      "diamondCt": 1.12,
      "netG": 5.524,
      "grossG": 6.61,
      "story": "At 4.31 carats a pair, this is Bloom's most confident statement in mint garnet — vivid pear-cut stones bordered in 1.12 carats of brilliant-cut diamonds and set in white gold. Worn together, they catch the light with the same quiet insistence the stone is named for.",
      "tone": "#6a9e7a",
      "images": [
        "img/products/gd25-1067.webp",
        "img/products/gd25-1067-1.webp"
      ],
      "hover": "img/products/gd25-1067-1.webp"
    },
    {
      "id": "gd25-994",
      "sku": "GD25-994",
      "name": "Aquamarine and diamond bloom bracelet",
      "collection": "Bloom",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Aquamarine",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 5.39,
      "diamondCt": 2.43,
      "netG": 16.826,
      "grossG": 18.39,
      "story": "Aquamarine is Bloom's stone for clarity and calm, and this bracelet wears it at scale: 5.39 carats of pear-cut aquamarine, sea-glass blue, set with 2.43 carats of brilliant-cut diamonds in white gold. It sits on the wrist like a held breath — cool, considered, unhurried.",
      "tone": "#7eb8c9",
      "images": [
        "img/products/gd25-994.webp",
        "img/products/gd25-994-1.webp",
        "img/products/gd25-994-2.webp"
      ],
      "hover": "img/products/gd25-994-1.webp"
    },
    {
      "id": "gd25-1026",
      "sku": "GD25-1026",
      "name": "Aquamarine and diamond bloom ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Aquamarine",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 2.14,
      "diamondCt": 1.07,
      "netG": 4.558,
      "grossG": 5.2,
      "story": "A ring in aquamarine's own colour of composure: 2.14 carats of pear-cut stone paired with 1.07 carats of diamonds, in white gold. Bloom reads the stone as courage worn quietly — the kind that doesn't need to announce itself.",
      "tone": "#7eb8c9",
      "images": [
        "img/products/gd25-1026.webp",
        "img/products/gd25-1026-1.webp",
        "img/products/gd25-1026-2.webp"
      ],
      "hover": "img/products/gd25-1026-1.webp"
    },
    {
      "id": "gd25-1086",
      "sku": "GD25-1086",
      "name": "Aquamarine and diamond bloom earring",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Aquamarine",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 3.51,
      "diamondCt": 1.08,
      "netG": 5.402,
      "grossG": 6.32,
      "story": "Aquamarine at its most luminous: 3.51 carats of pear-cut stone per pair, bordered in 1.08 carats of brilliant-cut diamonds and set in white gold. The blue deepens toward the tip of each pear, so the earrings shift in tone as they move.",
      "tone": "#7eb8c9",
      "images": [
        "img/products/gd25-1086.webp",
        "img/products/gd25-1086-1.webp"
      ],
      "hover": "img/products/gd25-1086-1.webp"
    },
    {
      "id": "gd25-1087",
      "sku": "GD25-1087",
      "name": "Aquamarine and diamond bloom pendant",
      "collection": "Bloom",
      "type": "Pendants",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Aquamarine",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 1.69,
      "diamondCt": 0.59,
      "netG": 2.484,
      "grossG": 2.94,
      "story": "The lightest piece in the aquamarine line — 1.69 carats of pear-cut stone with 0.59 carats of diamonds in white gold — sized to be worn without a second thought, which is exactly the point of a stone that stands for calm.",
      "tone": "#7eb8c9",
      "images": [
        "img/products/gd25-1087.webp"
      ]
    },
    {
      "id": "gd25-875",
      "sku": "GD25-875",
      "name": "Tanzanite and diamond bloom bracelet",
      "collection": "Bloom",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Tanzanite",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 8.5,
      "diamondCt": 2.38,
      "netG": 20.514,
      "grossG": 22.69,
      "story": "Tanzanite is mined in one place on earth and is rarer, gram for gram, than diamond — which is why Bloom reads it as a stone for new beginnings. This bracelet carries 8.5 carats of pear-cut tanzanite in a deep violet-blue, set with 2.38 carats of diamonds in white gold.",
      "tone": "#3a5f9a"
    },
    {
      "id": "gd25-964",
      "sku": "GD25-964",
      "name": "Pink spinel and diamond petal bracelet",
      "collection": "Bloom",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Mix",
      "stonePcs": null,
      "stoneCt": 1.56,
      "diamondCt": 1.67,
      "netG": 17.584,
      "grossG": 18.23,
      "story": "The Petal line takes pink spinel — Bloom's stone for healing and rebirth — and sets it in rounded, closed forms rather than open claws. This bracelet mixes round and pear-cut spinel totalling 1.56 carats with 1.67 carats of brilliant-cut diamonds, in white gold.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-964.webp"
      ]
    },
    {
      "id": "gd25-1096",
      "sku": "GD25-1096",
      "name": "Pink spinel and diamond petal earring",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": null,
      "stoneCt": 0.74,
      "diamondCt": 0.66,
      "netG": 5.26,
      "grossG": 5.54,
      "story": "A softer register of Petal: round pink spinel, 0.74 carats a pair, set with 0.66 carats of diamonds in rose gold. The warmth of the metal and the warmth of the stone were clearly meant to sit together.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-1096.webp",
        "img/products/gd25-1096-1.webp"
      ],
      "hover": "img/products/gd25-1096-1.webp"
    },
    {
      "id": "gd25-1095",
      "sku": "GD25-1095",
      "name": "Pink spinel and diamond petal ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": null,
      "stoneCt": 0.55,
      "diamondCt": 0.75,
      "netG": 4.05,
      "grossG": 4.31,
      "story": "Small enough to stack, considered enough to wear alone: 0.55 carats of round pink spinel with 0.75 carats of diamonds, set in rose gold as part of the Petal line.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-1095.webp",
        "img/products/gd25-1095-1.webp",
        "img/products/gd25-1095-2.webp"
      ],
      "hover": "img/products/gd25-1095-1.webp"
    },
    {
      "id": "gd25-1097",
      "sku": "GD25-1097",
      "name": "Pink spinel and diamond petal pendant",
      "collection": "Bloom",
      "type": "Pendants",
      "metal": "Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": null,
      "stoneCt": 0.64,
      "diamondCt": 0.46,
      "netG": 2.84,
      "grossG": 3.06,
      "story": "The Petal pendant keeps things simple — 0.64 carats of round pink spinel, 0.46 carats of diamonds, rose gold — for a piece meant to be worn constantly rather than saved for occasion.",
      "tone": "#c45a7a"
    },
    {
      "id": "gd26-790",
      "sku": "GD26-790",
      "name": "Pink spinel and spessartite bloom long chain",
      "collection": "Bloom",
      "type": "Necklaces",
      "metal": "18k White Gold",
      "metalCode": "G-18kt",
      "stone": "Pink Spinel & Spessartite",
      "shape": "Mix",
      "stonePcs": null,
      "stoneCt": 4.77,
      "diamondCt": 1.03,
      "netG": 9.25,
      "grossG": 10.41,
      "story": "A long chain that carries two stones at once: 0.94 carats of pink spinel for rebirth alongside 3.83 carats of spessartite for warmth, joined by 1.03 carats of brilliant-cut diamonds in 18k white gold. Worn open, it moves the way a garland does.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-790.webp"
      ]
    },
    {
      "id": "gd26-68",
      "sku": "GD26-68",
      "name": "Mint garnet and diamond garland necklace",
      "collection": "Bloom",
      "type": "Necklaces",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 13.27,
      "diamondCt": 6.19,
      "netG": 38.868,
      "grossG": 42.76,
      "story": "The Garland necklace is Bloom's largest gesture: 13.27 carats of pear-cut mint garnet strung with 6.19 carats of brilliant-cut diamonds in white gold, each stone hung like a leaf on a vine. It is built for the room, not the mirror.",
      "tone": "#6a9e7a",
      "images": [
        "img/products/gd26-68.webp",
        "img/products/gd26-68-1.webp"
      ],
      "hover": "img/products/gd26-68-1.webp"
    },
    {
      "id": "gd26-176",
      "sku": "GD26-176",
      "name": "Spessartite and diamond garland necklace",
      "collection": "Bloom",
      "type": "Necklaces",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Spessartite",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 17.28,
      "diamondCt": 5.88,
      "netG": 36.278,
      "grossG": 40.91,
      "story": "Spessartite burns a warmer orange than any other garnet, and this Garland necklace uses that heat generously — 17.28 carats of pear-cut stone with 5.88 carats of diamonds in white gold, strung to catch candlelight rather than daylight.",
      "tone": "#d4783a",
      "images": [
        "img/products/gd26-176.webp"
      ]
    },
    {
      "id": "gd26-513",
      "sku": "GD26-513",
      "name": "Chalcedony and spessartite floral motif long chain",
      "collection": "Bloom",
      "type": "Necklaces",
      "metal": "18k White Gold",
      "metalCode": "G-18kt",
      "stone": "Spessartite & Chalcedony",
      "shape": "Pears Cabs",
      "stonePcs": null,
      "stoneCt": 6.89,
      "diamondCt": 2.16,
      "netG": 17.742,
      "grossG": 29.82,
      "story": "A floral motif built from two very different textures: 6.89 carats of faceted spessartite set against 51.34 carats of carved, cabochon chalcedony, finished with 2.16 carats of round brilliant-cut diamonds in 18k white gold. Chalcedony is Bloom's stone for quiet renewal — matte where the spessartite is fire.",
      "tone": "#d4783a",
      "images": [
        "img/products/gd26-513.webp"
      ]
    },
    {
      "id": "gd26-219",
      "sku": "GD26-219",
      "name": "Fancy tanzanite and diamond flora pendant",
      "collection": "Bloom",
      "type": "Pendants",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Tanzanite",
      "shape": "Fancy",
      "stonePcs": null,
      "stoneCt": 4.87,
      "diamondCt": 2.05,
      "netG": 6.686,
      "grossG": 8.07,
      "story": "A fancy-cut tanzanite of 4.87 carats, faceted to hold more blue than a standard cut allows, set with 2.05 carats of diamonds in white gold. Part of the Flora line, where the stone is left as close to its rough shape as a fine setting allows.",
      "tone": "#3a5f9a"
    },
    {
      "id": "gnk0923-27",
      "sku": "GNK0923-27",
      "name": "Pink spinel and diamond petal necklace",
      "collection": "Bloom",
      "type": "Necklaces",
      "metal": "18k White Gold",
      "metalCode": "Gold 18K",
      "stone": "Pink Spinel",
      "shape": "Sq-Cushion",
      "stonePcs": null,
      "stoneCt": 8.96,
      "diamondCt": 1.85,
      "netG": 17.977,
      "grossG": 20.14,
      "story": "A square-cushion cut brings a more architectural pink spinel to the Petal line — 8.96 carats of it, paired with 1.85 carats of diamonds in 18k white gold, for a necklace with more presence than its siblings.",
      "tone": "#c45a7a"
    },
    {
      "id": "gd25-1046",
      "sku": "GD25-1046",
      "name": "Heart in bloom rubellite and diamond dual finger ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Rubellite",
      "shape": "Heart Cabs",
      "stonePcs": null,
      "stoneCt": 3.44,
      "diamondCt": 2.121,
      "netG": 8.468,
      "grossG": 9.58,
      "story": "Heart in Bloom sets a cabochon heart of rubellite — Bloom's stone for passion — across two fingers at once: 3.44 carats of stone, 2.121 carats of brilliant-cut diamonds, in white gold. It is a ring built to be noticed, and to move as the hand moves.",
      "tone": "#b8325a",
      "images": [
        "img/products/gd25-1046.webp",
        "img/products/gd25-1046-1.webp",
        "img/products/gd25-1046-2.webp"
      ],
      "hover": "img/products/gd25-1046-1.webp"
    },
    {
      "id": "gd25-124",
      "sku": "GD25-124",
      "name": "Pink spinel and diamond ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Pink Spinel",
      "shape": "Oval Cabs",
      "stonePcs": null,
      "stoneCt": 2.92,
      "diamondCt": 0.67,
      "netG": 7.506,
      "grossG": 8.224,
      "story": "A cabochon oval pink spinel, polished rather than faceted so its colour reads as pure saturation: 2.92 carats, set with 0.67 carats of diamonds in 18k white gold.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-124.webp"
      ]
    },
    {
      "id": "gd25-1036",
      "sku": "GD25-1036",
      "name": "Morganite, pink spinel and diamond feather ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White and Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel & Morganite",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 3.39,
      "diamondCt": 1.36,
      "netG": 8.02,
      "grossG": 8.97,
      "story": "The Feather ring pairs 1.81 carats of pear-cut pink spinel with 1.58 carats of morganite — one stone for rebirth, the other for tenderness — set with 1.36 carats of diamonds across white and rose gold, so the two metals echo the two stones.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-1036.webp"
      ]
    },
    {
      "id": "gd26-62",
      "sku": "GD26-62",
      "name": "Pink spinel and diamond rosette ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Drops",
      "stonePcs": null,
      "stoneCt": 4.21,
      "diamondCt": 1.05,
      "netG": 4.888,
      "grossG": 5.94,
      "story": "The Rosette line clusters drop-cut stones into a single dense bloom: 4.21 carats of pink spinel drops set with 1.05 carats of diamonds in white gold.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-62.webp",
        "img/products/gd26-62-1.webp"
      ],
      "hover": "img/products/gd26-62-1.webp"
    },
    {
      "id": "gd26-71",
      "sku": "GD26-71",
      "name": "Mint garnet and diamond garland ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 1.59,
      "diamondCt": 0.84,
      "netG": 4.344,
      "grossG": 4.83,
      "story": "A smaller Garland piece for the hand: 1.59 carats of pear-cut mint garnet, 0.84 carats of diamonds, white gold — the same vine motif as the necklace, scaled down to a single stone.",
      "tone": "#6a9e7a",
      "images": [
        "img/products/gd26-71.webp"
      ]
    },
    {
      "id": "gd26-139",
      "sku": "GD26-139",
      "name": "Heart in bloom tanzanite and diamond dual finger ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Tanzanite",
      "shape": "Heart",
      "stonePcs": null,
      "stoneCt": 4.02,
      "diamondCt": 2.05,
      "netG": 8.586,
      "grossG": 9.8,
      "story": "A heart-cut tanzanite of 4.02 carats spans two fingers in this Heart in Bloom ring, set with 2.05 carats of brilliant-cut diamonds in white gold — tanzanite's violet-blue standing in for new beginnings, worn boldly rather than quietly.",
      "tone": "#3a5f9a",
      "images": [
        "img/products/gd26-139.webp",
        "img/products/gd26-139-1.webp",
        "img/products/gd26-139-2.webp"
      ],
      "hover": "img/products/gd26-139-1.webp"
    },
    {
      "id": "gd26-167",
      "sku": "GD26-167",
      "name": "Spessartite and diamond rosette ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Spessartite",
      "shape": "Drops",
      "stonePcs": null,
      "stoneCt": 3.9,
      "diamondCt": 0.94,
      "netG": 5.252,
      "grossG": 6.22,
      "story": "Warm drop-cut spessartite gathered into a Rosette cluster — 3.9 carats of it, set with 0.94 carats of diamonds in white gold.",
      "tone": "#d4783a",
      "images": [
        "img/products/gd26-167.webp",
        "img/products/gd26-167-1.webp",
        "img/products/gd26-167-2.webp"
      ],
      "hover": "img/products/gd26-167-1.webp"
    },
    {
      "id": "gd26-200",
      "sku": "GD26-200",
      "name": "Pink spinel, aquamarine and diamond bloom statement ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel & Aquamarine",
      "shape": "Mix",
      "stonePcs": null,
      "stoneCt": 3.81,
      "diamondCt": 1.38,
      "netG": 8.182,
      "grossG": 9.22,
      "story": "A statement ring that puts two of Bloom's founding stones side by side: 2.46 carats of pink spinel for rebirth and 1.35 carats of aquamarine for clarity, set with 1.38 carats of diamonds in white gold.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-200.webp",
        "img/products/gd26-200-1.webp",
        "img/products/gd26-200-2.webp"
      ],
      "hover": "img/products/gd26-200-1.webp"
    },
    {
      "id": "gd26-201",
      "sku": "GD26-201",
      "name": "Spessartite, pink spinel and diamond bloom statement ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Spessartite & Pink Spinel",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 2.03,
      "diamondCt": 0.86,
      "netG": 5.562,
      "grossG": 6.14,
      "story": "Spessartite's warmth and pink spinel's rose sit together in this statement ring — 1.5 carats and 0.53 carats respectively, pear-cut, set with 0.86 carats of diamonds in white gold.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-201.webp",
        "img/products/gd26-201-1.webp",
        "img/products/gd26-201-2.webp"
      ],
      "hover": "img/products/gd26-201-1.webp"
    },
    {
      "id": "gd26-766",
      "sku": "GD26-766",
      "name": "Aquamarine, pink spinel and diamond bloom statement ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Aquamarine & Pink Spinel",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 2.09,
      "diamondCt": 0.96,
      "netG": 6.49,
      "grossG": 7.1,
      "story": "A cooler pairing for the same statement silhouette: 1.51 carats of pear-cut aquamarine beside 0.57 carats of pink spinel, set with 0.96 carats of diamonds in 18k white gold.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-766.webp"
      ]
    },
    {
      "id": "gd26-563",
      "sku": "GD26-563",
      "name": "Mint garnet and diamond bloom statement ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 1.84,
      "diamondCt": 1.01,
      "netG": 6.01,
      "grossG": 6.58,
      "story": "Mint garnet alone, given the full statement treatment: 1.84 carats of pear-cut stone set with 1.01 carats of diamonds in 18k white gold — bolder in scale than the earlier Garland ring, though the meaning stays the same.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd26-205",
      "sku": "GD26-205",
      "name": "Lavender tanzanite, tanzanite and diamond fern ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Tanzanite",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 7.23,
      "diamondCt": 0.56,
      "netG": 7.402,
      "grossG": 8.96,
      "story": "The Fern ring holds two shades of tanzanite at once — lavender and deep blue, 7.23 carats combined — with a comparatively restrained 0.56 carats of diamonds in white gold, so the stone itself carries the piece.",
      "tone": "#3a5f9a",
      "images": [
        "img/products/gd26-205.webp"
      ]
    },
    {
      "id": "gd26-206",
      "sku": "GD26-206",
      "name": "Spessartite, pink spinel and diamond fern ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel & Spessartite",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 8.75,
      "diamondCt": 0.58,
      "netG": 7.324,
      "grossG": 9.19,
      "story": "A second Fern ring in warmer tones: 7.71 carats of spessartite beside 1.04 carats of pink spinel, again with a light 0.58 carats of diamonds in white gold, letting colour do most of the work.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-206.webp"
      ]
    },
    {
      "id": "gd26-257",
      "sku": "GD26-257",
      "name": "Spessartite and diamond garland ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Spessartite",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 1.9,
      "diamondCt": 0.83,
      "netG": 4.594,
      "grossG": 5.14,
      "story": "A single pear-cut spessartite of 1.9 carats, set with 0.83 carats of diamonds in white gold — the Garland motif reduced to its simplest form.",
      "tone": "#d4783a",
      "images": [
        "img/products/gd26-257.webp",
        "img/products/gd26-257-1.webp",
        "img/products/gd26-257-2.webp"
      ],
      "hover": "img/products/gd26-257-1.webp"
    },
    {
      "id": "gd26-566",
      "sku": "GD26-566",
      "name": "Heart in bloom crystal and tanzanite dual finger ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Tanzanite & Crystal",
      "shape": "Heart",
      "stonePcs": null,
      "stoneCt": 12.37,
      "diamondCt": 0.45,
      "netG": 4.216,
      "grossG": 6.78,
      "story": "Carved rock crystal wraps 10.74 carats around a 1.63 carat heart-cut tanzanite in this dual finger ring, finished with 0.45 carats of diamonds in 18k white gold. Crystal stands for clarity in Bloom's language — here it is literal, framing the tanzanite like glass around a flame.",
      "tone": "#3a5f9a",
      "images": [
        "img/products/gd26-566.webp"
      ]
    },
    {
      "id": "gd26-581",
      "sku": "GD26-581",
      "name": "Petal ring in Malaya garnet and diamond",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Malaya Garnet",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 9.76,
      "diamondCt": 1.905,
      "netG": 6.407,
      "grossG": 8.74,
      "story": "Malaya garnet burns a warmer orange-red than most garnets, and this Petal ring gives it room to do so: 9.76 carats of pear-cut stone set with 1.905 carats of diamonds in 18k white gold.",
      "tone": "#c47858",
      "images": [
        "img/products/gd26-581.webp"
      ]
    },
    {
      "id": "gd26-583",
      "sku": "GD26-583",
      "name": "Spessartite and diamond bloom statement ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Spessartite",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 2.34,
      "diamondCt": 1.01,
      "netG": 6.15,
      "grossG": 6.82,
      "story": "Spessartite given the statement treatment: 2.34 carats of pear-cut stone, 1.01 carats of diamonds, 18k white gold.",
      "tone": "#d4783a",
      "images": [
        "img/products/gd26-583.webp"
      ]
    },
    {
      "id": "gd25-1047",
      "sku": "GD25-1047",
      "name": "Heart in bloom rubellite and diamond ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Rubellite",
      "shape": "Heart Cabs",
      "stonePcs": null,
      "stoneCt": 2.22,
      "diamondCt": 2,
      "netG": 4.716,
      "grossG": 5.56,
      "story": "A single cabochon heart of rubellite, 2.22 carats, set with 2 carats of brilliant-cut diamonds in rose gold — the single-finger companion to the dual-finger Heart in Bloom ring, quieter but no less deliberate.",
      "tone": "#b8325a",
      "images": [
        "img/products/gd25-1047.webp",
        "img/products/gd25-1047-1.webp",
        "img/products/gd25-1047-2.webp"
      ],
      "hover": "img/products/gd25-1047-1.webp"
    },
    {
      "id": "gd26-587",
      "sku": "GD26-587",
      "name": "Fancy tanzanite and diamond flora ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Tanzanite",
      "shape": "Fancy",
      "stonePcs": null,
      "stoneCt": 4.09,
      "diamondCt": 1.87,
      "netG": 9.678,
      "grossG": 10.87,
      "story": "A fancy-cut tanzanite of 4.09 carats, part of the Flora line, set with 1.87 carats of diamonds in 18k white gold — the stone left in an unconventional shape that favours colour over symmetry.",
      "tone": "#3a5f9a",
      "images": [
        "img/products/gd26-587.webp"
      ]
    },
    {
      "id": "gd25-816",
      "sku": "GD25-816",
      "name": "In bloom pink spinel and diamond hoop",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Pink Spinel",
      "shape": "Oval Cabs",
      "stonePcs": null,
      "stoneCt": 5.33,
      "diamondCt": 5.15,
      "netG": 30.134,
      "grossG": 32.23,
      "story": "A cabochon hoop that puts nearly equal weight in stone and diamond: 5.33 carats of oval pink spinel against 5.15 carats of brilliant-cut diamonds, set in 18k white gold — one of the more architectural pieces in Bloom.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-816.webp",
        "img/products/gd25-816-2.webp"
      ],
      "hover": "img/products/gd25-816-2.webp"
    },
    {
      "id": "gd25-435",
      "sku": "GD25-435",
      "name": "Heart in bloom pink rubellite earrings",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "18k Rose Gold",
      "metalCode": "G-18kt-W",
      "stone": "Rubellite",
      "shape": "Heart cab",
      "stonePcs": null,
      "stoneCt": 5.8,
      "diamondCt": 6.9,
      "netG": 21.16,
      "grossG": 23.7,
      "story": "The largest rubellite in the Heart in Bloom line: cabochon hearts of 5.8 carats a pair, framed in 6.9 carats of brilliant-cut diamonds and set in rose gold — passion, at full scale, for the ears.",
      "tone": "#b8325a"
    },
    {
      "id": "gd26-256",
      "sku": "GD26-256",
      "name": "Spessartite and diamond garland bracelet",
      "collection": "Bloom",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Spessartite",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 4.5,
      "diamondCt": 2.08,
      "netG": 18.414,
      "grossG": 19.73,
      "story": "A Garland bracelet in spessartite: 4.5 carats of pear-cut stone linked with 2.08 carats of diamonds in white gold, the vine motif worn flat along the wrist.",
      "tone": "#d4783a"
    },
    {
      "id": "gd26-69",
      "sku": "GD26-69",
      "name": "Mint garnet and diamond garland bracelet",
      "collection": "Bloom",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 3.3,
      "diamondCt": 2.12,
      "netG": 18.086,
      "grossG": 19.17,
      "story": "The same Garland line in mint garnet — 3.3 carats of pear-cut stone with 2.12 carats of diamonds in white gold — cooler and quieter than its spessartite counterpart.",
      "tone": "#6a9e7a",
      "images": [
        "img/products/gd26-69.webp",
        "img/products/gd26-69-1.webp",
        "img/products/gd26-69-2.webp"
      ],
      "hover": "img/products/gd26-69-2.webp"
    },
    {
      "id": "gd26-63",
      "sku": "GD26-63",
      "name": "Pink spinel and diamond rosette bracelet",
      "collection": "Bloom",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Drops",
      "stonePcs": null,
      "stoneCt": 17.61,
      "diamondCt": 2.42,
      "netG": 17.774,
      "grossG": 21.78,
      "story": "The Rosette line's largest bracelet: 17.61 carats of drop-cut pink spinel clustered with 2.42 carats of diamonds in white gold, dense enough to read as a cuff rather than a chain.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-63.webp",
        "img/products/gd26-63-1.webp",
        "img/products/gd26-63-2.webp"
      ],
      "hover": "img/products/gd26-63-2.webp"
    },
    {
      "id": "gd26-aq-br",
      "sku": "GD26-AQ-BR",
      "name": "Aquamarine and diamond bloom bracelet",
      "collection": "Bloom",
      "type": "Bracelets",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Aquamarine",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 1.78,
      "diamondCt": 0.88,
      "netG": 4.528,
      "grossG": 5.06,
      "story": "A lighter aquamarine bracelet for everyday wear: 1.78 carats of pear-cut stone with 0.88 carats of diamonds in 18k white gold.",
      "tone": "#7eb8c9"
    },
    {
      "id": "gd26-762",
      "sku": "GD26-762",
      "name": "Pink spinel and diamond bloom bracelet",
      "collection": "Bloom",
      "type": "Bracelets",
      "metal": "18k White and Rose Gold",
      "metalCode": "G-18kt-WR",
      "stone": "Pink Spinel",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 2.15,
      "diamondCt": 0.97,
      "netG": 4.126,
      "grossG": 4.75,
      "story": "Pink spinel across two golds at once: 2.15 carats of pear-cut stone with 0.97 carats of diamonds, set in a mix of white and rose gold.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-762.webp"
      ]
    },
    {
      "id": "gd25-288",
      "sku": "GD25-288",
      "name": "Pink spinel and diamond bud earring",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Pink Spinel",
      "shape": "Oval Cabs",
      "stonePcs": null,
      "stoneCt": 7.8,
      "diamondCt": 1.55,
      "netG": 12.4,
      "grossG": 14.27,
      "story": "The Bud earring keeps pink spinel in cabochon form — 7.8 carats of oval stone per pair, edged in 1.55 carats of brilliant-cut diamonds and set in 18k white gold — closed and rounded, the way a flower looks before it opens.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-288.webp",
        "img/products/gd25-288-1.webp"
      ],
      "hover": "img/products/gd25-288-1.webp"
    },
    {
      "id": "gd25-915-a",
      "sku": "GD25-915 A",
      "name": "Pink spinel and diamond bloom studs",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "Yellow Gold",
      "metalCode": "G-14kt-Y",
      "stone": "Pink Spinel",
      "shape": "Balls",
      "stonePcs": null,
      "stoneCt": 17.75,
      "diamondCt": 0.82,
      "netG": 15.926,
      "grossG": 19.64,
      "story": "Ball-cut pink spinel drops give these studs unusual movement: 17.75 carats of stone with 0.82 carats of diamonds, set in yellow gold — the warmest metal in the collection paired with Bloom's stone for love.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd25-915-a.webp"
      ]
    },
    {
      "id": "gd26-60",
      "sku": "GD26-60",
      "name": "Pink spinel and diamond rosette studs",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Drops",
      "stonePcs": null,
      "stoneCt": 9.8,
      "diamondCt": 3.22,
      "netG": 15.246,
      "grossG": 17.85,
      "story": "A dense Rosette cluster for the ear: 9.8 carats of drop-cut pink spinel with 3.22 carats of diamonds in white gold.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-60.webp",
        "img/products/gd26-60-2.webp"
      ],
      "hover": "img/products/gd26-60-2.webp"
    },
    {
      "id": "gd26-70",
      "sku": "GD26-70",
      "name": "Mint garnet and diamond garland earring",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 4.56,
      "diamondCt": 1.1,
      "netG": 11.868,
      "grossG": 13,
      "story": "Garland's earring: 4.56 carats of pear-cut mint garnet per pair, set with 1.1 carats of diamonds in white gold.",
      "tone": "#6a9e7a",
      "images": [
        "img/products/gd26-70.webp"
      ]
    },
    {
      "id": "gd26-166",
      "sku": "GD26-166",
      "name": "Spessartite and diamond rosette studs",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Spessartite",
      "shape": "Drops",
      "stonePcs": null,
      "stoneCt": 25.65,
      "diamondCt": 3.39,
      "netG": 15.392,
      "grossG": 21.2,
      "story": "At 25.65 carats a pair, this is the single largest stone weight anywhere in Bloom — drop-cut spessartite in full, fiery scale, set with 3.39 carats of diamonds in white gold.",
      "tone": "#d4783a",
      "images": [
        "img/products/gd26-166.webp",
        "img/products/gd26-166-2.webp"
      ],
      "hover": "img/products/gd26-166-2.webp"
    },
    {
      "id": "gd26-177",
      "sku": "GD26-177",
      "name": "Spessartite and diamond garland earring",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Spessartite",
      "shape": "Pears",
      "stonePcs": null,
      "stoneCt": 6.63,
      "diamondCt": 1.15,
      "netG": 10.704,
      "grossG": 12.26,
      "story": "A quieter spessartite pairing: 6.63 carats of pear-cut stone with 1.15 carats of diamonds in white gold, in the Garland line's vine setting.",
      "tone": "#d4783a",
      "images": [
        "img/products/gd26-177.webp"
      ]
    },
    {
      "id": "gd26-210",
      "sku": "GD26-210",
      "name": "Pink spinel and diamond rosette studs rose",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "White and Rose Gold",
      "metalCode": "G-14kt-WR",
      "stone": "Pink Spinel",
      "shape": "Drops",
      "stonePcs": null,
      "stoneCt": 14.42,
      "diamondCt": 2.97,
      "netG": 15.342,
      "grossG": 18.82,
      "story": "A Rosette stud in mixed metal: 14.42 carats of drop-cut pink spinel with 2.97 carats of diamonds, set across white and rose gold.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-210.webp"
      ]
    },
    {
      "id": "gd26-228-b",
      "sku": "GD26-228 B",
      "name": "Fancy tanzanite and diamond flora studs",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Tanzanite",
      "shape": "Fancy",
      "stonePcs": null,
      "stoneCt": 10.32,
      "diamondCt": 2.85,
      "netG": 14.406,
      "grossG": 17.04,
      "story": "Fancy-cut tanzanite at full scale: 10.32 carats a pair, set with 2.85 carats of diamonds in white gold — the boldest piece in the Flora line.",
      "tone": "#3a5f9a",
      "images": [
        "img/products/gd26-228-b.webp"
      ]
    },
    {
      "id": "gd26-785",
      "sku": "GD26-785",
      "name": "Spessartite, pink spinel and diamond garland earring",
      "collection": "Bloom",
      "type": "Earrings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Pink Spinel & Spessartite",
      "shape": "Mix",
      "stonePcs": null,
      "stoneCt": 4.21,
      "diamondCt": 0.97,
      "netG": 7.164,
      "grossG": 8.2,
      "story": "A Garland earring that mixes stones: 3.71 carats of spessartite beside 0.5 carats of pink spinel, set with 0.97 carats of diamonds in 18k white gold — warmth and rose meeting in the same setting.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-785.webp"
      ]
    },
    {
      "id": "gd26-61",
      "sku": "GD26-61",
      "name": "Pink spinel and diamond dew pendant",
      "collection": "Bloom",
      "type": "Pendants",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Drops",
      "stonePcs": 18,
      "stoneCt": 5.41,
      "diamondCt": 1.9,
      "netG": 9.108,
      "grossG": 10.57,
      "story": "Crafted in White Gold, set with 5.41 carats of drop-cut pink spinel paired with 1.9 carats of brilliant cut diamonds.",
      "tone": "#c45a7a",
      "images": [
        "img/products/gd26-61-1.webp"
      ]
    },
    {
      "id": "gd26-81",
      "sku": "GD26-81",
      "name": "Pink spinel and diamond dew ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Mix",
      "stonePcs": 11,
      "stoneCt": 4.45,
      "diamondCt": 0.42,
      "netG": 3.676,
      "grossG": 4.65,
      "story": "Crafted in White Gold, set with 4.45 carats of mixed ball, pear and drop-cut pink spinel paired with 0.42 carats of brilliant cut diamonds.",
      "tone": "#c45a7a"
    },
    {
      "id": "gd26-80",
      "sku": "GD26-80",
      "name": "Pink spinel and diamond dew bracelet",
      "collection": "Bloom",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Mix",
      "stonePcs": 22,
      "stoneCt": 9.5,
      "diamondCt": 2.24,
      "netG": 15.212,
      "grossG": 17.56,
      "story": "Crafted in White Gold, set with 9.5 carats of mixed ball, pear and drop-cut pink spinel paired with 2.24 carats of brilliant cut diamonds.",
      "tone": "#c45a7a"
    },
    {
      "id": "g-625",
      "sku": "G 625",
      "name": "Mint garnet, pink spinel and diamond dew ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet & Pink Spinel",
      "shape": "Mix",
      "stonePcs": 14,
      "stoneCt": 5.77,
      "diamondCt": 0.46,
      "netG": 7.767,
      "grossG": 9.013,
      "story": "Crafted in White Gold, set with 3.99 carats of pear-cut mint garnet alongside 1.78 carats of oval cut pink spinel, paired with 0.46 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd23-146",
      "sku": "GD23-146",
      "name": "Mint garnet, pink spinel and diamond dew ring",
      "collection": "Bloom",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet & Pink Spinel",
      "shape": "Marquise & Round",
      "stonePcs": 15,
      "stoneCt": 4.05,
      "diamondCt": 1.221,
      "netG": 8.93,
      "grossG": 9.984,
      "story": "Crafted in White Gold, set with 3.5 carats of marquise cut mint garnet alongside 0.55 carats of round cut pink spinel, paired with 1.221 carats of round and baguette cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd26-198-a",
      "sku": "GD26-198 A",
      "name": "Aquamarine and diamond swirl necklace",
      "collection": "Swirl",
      "type": "Necklaces",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Aquamarine",
      "shape": "Round",
      "stonePcs": 8,
      "stoneCt": 2.29,
      "diamondCt": 2.17,
      "netG": 30.788,
      "grossG": 31.68,
      "story": "Crafted in White Gold, set with 2.29 carats of round cut aquamarine paired with 2.17 carats of brilliant cut diamonds.",
      "tone": "#7eb8c9"
    },
    {
      "id": "gd26-786",
      "sku": "GD26-786",
      "name": "Mint garnet and diamond swirl necklace",
      "collection": "Swirl",
      "type": "Necklaces",
      "metal": "18k White Gold",
      "metalCode": "G-18kt",
      "stone": "Mint Garnet",
      "shape": "Round",
      "stonePcs": 9,
      "stoneCt": 2.55,
      "diamondCt": 4.75,
      "netG": 34.9,
      "grossG": 36.36,
      "story": "Crafted in 18k White Gold, set with 2.55 carats of round cut mint garnet paired with 4.75 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd26-242",
      "sku": "GD26-242",
      "name": "Mint garnet and diamond swirl necklace",
      "collection": "Swirl",
      "type": "Necklaces",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Round",
      "stonePcs": 18,
      "stoneCt": 6.51,
      "diamondCt": 12.7,
      "netG": 61.028,
      "grossG": 64.87,
      "story": "Crafted in White Gold, set with 6.51 carats of round cut mint garnet paired with 12.7 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd26-242-a",
      "sku": "GD26-242 A",
      "name": "Mint garnet and diamond swirl earring",
      "collection": "Swirl",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Round",
      "stonePcs": 2,
      "stoneCt": 1.4,
      "diamondCt": 1.68,
      "netG": 7.204,
      "grossG": 7.82,
      "story": "Crafted in White Gold, set with 1.4 carats of round cut mint garnet paired with 1.68 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd25-974",
      "sku": "GD25-974",
      "name": "Pink spinel and diamond swirl earring",
      "collection": "Swirl",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 6,
      "stoneCt": 2.63,
      "diamondCt": 1.455,
      "netG": 7.753,
      "grossG": 8.57,
      "story": "Crafted in White Gold, set with 2.63 carats of round cut pink spinel paired with 1.455 carats of brilliant cut diamonds.",
      "tone": "#c45a7a"
    },
    {
      "id": "gd25-1055",
      "sku": "GD25-1055",
      "name": "Mint garnet and diamond swirl earring",
      "collection": "Swirl",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Round",
      "stonePcs": 8,
      "stoneCt": 3.12,
      "diamondCt": 0.62,
      "netG": 5.252,
      "grossG": 6,
      "story": "Crafted in White Gold, set with 3.12 carats of round cut mint garnet paired with 0.62 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd25-1074",
      "sku": "GD25-1074",
      "name": "Aquamarine and diamond swirl earring",
      "collection": "Swirl",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Aquamarine",
      "shape": "Round",
      "stonePcs": 8,
      "stoneCt": 2.28,
      "diamondCt": 0.62,
      "netG": 4.84,
      "grossG": 5.42,
      "story": "Crafted in White Gold, set with 2.28 carats of round cut aquamarine paired with 0.62 carats of brilliant cut diamonds.",
      "tone": "#7eb8c9"
    },
    {
      "id": "gd26-198-b",
      "sku": "GD26-198 B",
      "name": "Aquamarine and diamond swirl earring",
      "collection": "Swirl",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Aquamarine",
      "shape": "Round",
      "stonePcs": 2,
      "stoneCt": 0.75,
      "diamondCt": 1.34,
      "netG": 6.132,
      "grossG": 6.55,
      "story": "Crafted in White Gold, set with 0.75 carats of round cut aquamarine paired with 1.34 carats of brilliant cut diamonds.",
      "tone": "#7eb8c9"
    },
    {
      "id": "gd26-782",
      "sku": "GD26-782",
      "name": "Mint garnet and diamond swirl earring",
      "collection": "Swirl",
      "type": "Earrings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": 2,
      "stoneCt": 1.11,
      "diamondCt": 1.35,
      "netG": 6.988,
      "grossG": 7.48,
      "story": "Crafted in 18k White Gold, set with 1.11 carats of pear-cut mint garnet paired with 1.35 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd26-150",
      "sku": "GD26-150",
      "name": "Spessartite and diamond swirl earring",
      "collection": "Swirl",
      "type": "Earrings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Spessartite",
      "shape": "Drops",
      "stonePcs": 2,
      "stoneCt": 5.11,
      "diamondCt": 0.25,
      "netG": 2.448,
      "grossG": 3.52,
      "story": "Crafted in White Gold, set with 5.11 carats of drop-cut spessartite paired with 0.25 carats of brilliant cut diamonds.",
      "tone": "#d4783a"
    },
    {
      "id": "gd25-991",
      "sku": "GD25-991",
      "name": "Pink spinel and diamond swirl ring",
      "collection": "Swirl",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 4,
      "stoneCt": 1.21,
      "diamondCt": 0.74,
      "netG": 4.06,
      "grossG": 4.45,
      "story": "Crafted in White Gold, set with 1.21 carats of round cut pink spinel paired with 0.74 carats of brilliant cut diamonds.",
      "tone": "#c45a7a"
    },
    {
      "id": "gd25-1025",
      "sku": "GD25-1025",
      "name": "Aquamarine and diamond swirl ring",
      "collection": "Swirl",
      "type": "Rings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Aquamarine",
      "shape": "Round",
      "stonePcs": 4,
      "stoneCt": 0.95,
      "diamondCt": 0.79,
      "netG": 4.622,
      "grossG": 4.97,
      "story": "Crafted in 18k White Gold, set with 0.95 carats of round cut aquamarine paired with 0.79 carats of brilliant cut diamonds.",
      "tone": "#7eb8c9"
    },
    {
      "id": "gd25-1057",
      "sku": "GD25-1057",
      "name": "Mint garnet and diamond swirl ring",
      "collection": "Swirl",
      "type": "Rings",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Round",
      "stonePcs": 4,
      "stoneCt": 1.24,
      "diamondCt": 0.71,
      "netG": 4.11,
      "grossG": 4.5,
      "story": "Crafted in White Gold, set with 1.24 carats of round cut mint garnet paired with 0.71 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd26-783",
      "sku": "GD26-783",
      "name": "Mint garnet and diamond swirl ring",
      "collection": "Swirl",
      "type": "Rings",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Mint Garnet",
      "shape": "Round",
      "stonePcs": 5,
      "stoneCt": 1.39,
      "diamondCt": 0.95,
      "netG": 8.162,
      "grossG": 8.63,
      "story": "Crafted in 18k White Gold, set with 1.39 carats of round cut mint garnet paired with 0.95 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd25-894",
      "sku": "GD25-894",
      "name": "Aquamarine and diamond swirl bracelet",
      "collection": "Swirl",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Aquamarine",
      "shape": "Round",
      "stonePcs": 7,
      "stoneCt": 1.82,
      "diamondCt": 1.5,
      "netG": 12.426,
      "grossG": 13.09,
      "story": "Crafted in White Gold, set with 1.82 carats of round cut aquamarine paired with 1.5 carats of brilliant cut diamonds.",
      "tone": "#7eb8c9"
    },
    {
      "id": "gd25-966",
      "sku": "GD25-966",
      "name": "Pink spinel and diamond swirl bracelet",
      "collection": "Swirl",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 5,
      "stoneCt": 3.4,
      "diamondCt": 1.84,
      "netG": 23.732,
      "grossG": 24.78,
      "story": "Crafted in White Gold, set with 3.4 carats of round cut pink spinel paired with 1.84 carats of brilliant cut diamonds.",
      "tone": "#c45a7a"
    },
    {
      "id": "gd25-992",
      "sku": "GD25-992",
      "name": "Pink spinel and diamond swirl bracelet",
      "collection": "Swirl",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Pink Spinel",
      "shape": "Round",
      "stonePcs": 7,
      "stoneCt": 2.22,
      "diamondCt": 1.6,
      "netG": 13.516,
      "grossG": 14.28,
      "story": "Crafted in White Gold, set with 2.22 carats of round cut pink spinel paired with 1.6 carats of brilliant cut diamonds.",
      "tone": "#c45a7a"
    },
    {
      "id": "gd25-1083",
      "sku": "GD25-1083",
      "name": "Mint garnet and diamond swirl bracelet",
      "collection": "Swirl",
      "type": "Bracelets",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Mint Garnet",
      "shape": "Round",
      "stonePcs": 5,
      "stoneCt": 1.84,
      "diamondCt": 1.72,
      "netG": 14.158,
      "grossG": 14.87,
      "story": "Crafted in White Gold, set with 1.84 carats of round cut mint garnet paired with 1.72 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd26-827",
      "sku": "GD26-827",
      "name": "Mint garnet and diamond swirl pendant",
      "collection": "Swirl",
      "type": "Pendants",
      "metal": "18k White Gold",
      "metalCode": "G-18kt-W",
      "stone": "Mint Garnet",
      "shape": "Pears",
      "stonePcs": 1,
      "stoneCt": 0.79,
      "diamondCt": 0.88,
      "netG": 6.616,
      "grossG": 6.95,
      "story": "Crafted in 18k White Gold, set with 0.79 carats of pear-cut mint garnet paired with 0.88 carats of brilliant cut diamonds.",
      "tone": "#6a9e7a"
    },
    {
      "id": "gd26-149",
      "sku": "GD26-149",
      "name": "Spessartite and diamond swirl pendant",
      "collection": "Swirl",
      "type": "Pendants",
      "metal": "White Gold",
      "metalCode": "G-14kt-W",
      "stone": "Spessartite",
      "shape": "Drops",
      "stonePcs": 1,
      "stoneCt": 2.92,
      "diamondCt": 0.14,
      "netG": 0.628,
      "grossG": 1.24,
      "story": "Crafted in White Gold, set with 2.92 carats of drop-cut spessartite paired with 0.14 carats of brilliant cut diamonds.",
      "tone": "#d4783a"
    },
    {
      "id": "gd25-431",
      "sku": "GD25-431",
      "name": "Rubellite and diamond swirl pendant",
      "collection": "Swirl",
      "type": "Pendants",
      "metal": "18k Rose Gold",
      "metalCode": "G-18kt-R",
      "stone": "Rubellite",
      "shape": "Pears Cabs",
      "stonePcs": 1,
      "stoneCt": 3.66,
      "diamondCt": 0.27,
      "netG": 2.154,
      "grossG": 2.94,
      "story": "Crafted in 18k Rose Gold, set with 3.66 carats of cabochon pear-cut rubellite paired with 0.27 carats of brilliant cut diamonds.",
      "tone": "#b8325a"
    }
  ]
};
