/* Fine Jewellery catalog — Bloom & Safar
   Generated from client product lists. Images pending; cards use stone tone. */
window.FJ_DATA = {
  collections: [
  {
    "id": "bloom",
    "name": "Bloom",
    "lede": "Cycles of life. Every person blooms differently.",
    "story": "Just as a flower is cultivated for its beauty, the effort it takes to get to that stage often goes unnoticed. From sowing the seed, to becoming a sapling and eventually blooming into a flower.\n\nDrawing a parallel to life: the day we achieve our goal, we take a moment to look back and appreciate the challenges, effort and patience it took to get there. Hence, Bloom.\n\nThe different gemstones represent that every person has a different way of blooming. Mint garnet for quiet strength, growth and harmony. Aquamarine for clarity, courage and calmness. Tanzanite for new beginnings, the rarity of life's special moments, and wisdom. Pink spinel for healing, rebirth and love.\n\nStones used: mint garnet, aquamarine, tanzanite and pink spinel. Set in white gold.",
    "tone": "#6a9e7a",
    "banner": "img/bloom-banner.png",
    "meta": "Mint garnet · Aquamarine · Tanzanite · Pink spinel · White gold"
  },
  {
    "id": "safar",
    "name": "Safar",
    "lede": "A journey through time. Designed with Shantanu Garg.",
    "story": "The Safar collection is inspired by a journey through time where Indian architectural heritage and modern expression converge into a singular narrative.\n\nInfluenced by the geometry, symmetry and intricate ornamentation of temple and Mughal architecture, and developed in collaboration with Shantanu Garg, each piece transforms traditional motifs into fluid, contemporary forms, reinterpreting India's architectural vocabulary into a modern, wearable expression.\n\nStructured yet effortless, the designs are conceived to be versatile and transformable, adapting seamlessly to the wearer while retaining their architectural essence.\n\nSafar embodies movement not just in form, but in meaning, capturing the evolution of design across cultures, reimagined for the present.",
    "tone": "#c45a7a",
    "banner": "img/safar-banner.png",
    "designer": "Shantanu Garg",
    "meta": "Designed with Shantanu Garg"
  }
],
  types: ["Necklaces", "Pendants", "Earrings", "Rings", "Bracelets"],
  products: [
  {
    "id": "gd26-148",
    "sku": "GD26-148",
    "name": "Tanzanite and diamond cuff bracelet",
    "collection": "Safar",
    "type": "Bracelets",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Tanzanite",
    "shape": "Round",
    "stonePcs": 1,
    "stoneCt": 0.27,
    "diamondCt": 1.94,
    "netG": 11.768,
    "grossG": 12.21,
    "story": "Crafted in 14k White gold, set with 0.27 carats of intense blue tanzanite paired with 1.94 carats of brilliant cut diamonds",
    "tone": "#3a5f9a"
  },
  {
    "id": "gd25-1103",
    "sku": "GD25-1103",
    "name": "Pink spinel and diamond cuff bracelet",
    "collection": "Safar",
    "type": "Bracelets",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel",
    "shape": "Round",
    "stonePcs": 1,
    "stoneCt": 0.24,
    "diamondCt": 2.07,
    "netG": 11.748,
    "grossG": 12.21,
    "story": "Crafted in 14k White gold, set with 0.24 carats of vivid pink spinel paired with 2.07 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-196-c",
    "sku": "GD26-196 C",
    "name": "Pink spinel and diamond motif bracelet",
    "collection": "Safar",
    "type": "Bracelets",
    "metal": "14k White and Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel",
    "shape": "Round",
    "stonePcs": 1,
    "stoneCt": 0.41,
    "diamondCt": 1.08,
    "netG": 6.582,
    "grossG": 6.88,
    "story": "Crafted in 14k Rose gold, set with 0.41 carats of vivid pink spinel paired with 1.08 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-197-c",
    "sku": "GD26-197 C",
    "name": "Dual motif pink spinel and diamond bracelet",
    "collection": "Safar",
    "type": "Bracelets",
    "metal": "14k White and Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel",
    "shape": "Hexagon",
    "stonePcs": 8,
    "stoneCt": 1.36,
    "diamondCt": 1.356,
    "netG": 12.957,
    "grossG": 13.5,
    "story": "Crafted in 14k Rose gold, set with 1.36 carats of hexagon cut pink spinel paired with 1.35 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-224",
    "sku": "GD26-224",
    "name": "Pink spinel and diamond multi motif bracelet",
    "collection": "Safar",
    "type": "Bracelets",
    "metal": "14k White and Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel",
    "shape": "Round",
    "stonePcs": 5,
    "stoneCt": 0.5,
    "diamondCt": 2.18,
    "netG": 25.884,
    "grossG": 26.42,
    "story": "Crafted in 14k Rose gold, set with 0.5 carats of pink spinel paired with 2.18 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-275-a",
    "sku": "GD26-275 A",
    "name": "Pink spinel and diamond statement bracelet",
    "collection": "Safar",
    "type": "Bracelets",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel",
    "shape": "Beads",
    "stonePcs": 21,
    "stoneCt": 20.1,
    "diamondCt": 10.3,
    "netG": 33.67,
    "grossG": 39.75,
    "story": "Crafted in 14k Rose gold, set with 20.1 carats of custom bead cut pink spinel paired with 10.3 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-294",
    "sku": "GD25-294",
    "name": "Mix metal pink spinel and diamond safar motif earring",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "18k Rose Gold",
    "metalCode": "G-18kt-R",
    "stone": "Pink Spinel",
    "shape": "Round",
    "stonePcs": 2,
    "stoneCt": 0.72,
    "diamondCt": 2.68,
    "netG": 15.95,
    "grossG": 16.63,
    "story": "Crafted in 18k Rose and white gold, set with 0.72 carats of pink spinel paired with 2.68 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-842",
    "sku": "GD25-842",
    "name": "Rose rhodolite and diamond danglers",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "18k Rose Gold",
    "metalCode": "G-18kt-R",
    "stone": "Rose Rhodolite",
    "shape": "Pears",
    "stonePcs": 2,
    "stoneCt": 4.77,
    "diamondCt": 1.62,
    "netG": 10.482,
    "grossG": 11.76,
    "story": "Crafted in 18k White gold, set with 4.77 carats of Pear shaped Rose Rhodolite paired with 1.62 carats of brilliant cut diamonds",
    "tone": "#9a3a6a"
  },
  {
    "id": "gd26-140",
    "sku": "GD26-140",
    "name": "Morganite and diamond danglers",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "18k Rose Gold",
    "metalCode": "G-18kt-R",
    "stone": "Morganite",
    "shape": "Oval",
    "stonePcs": 2,
    "stoneCt": 4.33,
    "diamondCt": 1.15,
    "netG": 6.464,
    "grossG": 7.56,
    "story": "Crafted in 18k White gold, set with 4.33 carats of Oval Morganite paired with 1.15 carats of brilliant cut diamonds",
    "tone": "#e8b4b8"
  },
  {
    "id": "gd26-146",
    "sku": "GD26-146",
    "name": "Pink spinel and diamond hoop",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "14k White and Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel",
    "shape": "Round",
    "stonePcs": 52,
    "stoneCt": 1.52,
    "diamondCt": 0.7,
    "netG": 12.166,
    "grossG": 12.61,
    "story": "Crafted in 14k White gold, set with 1.52 carats of vivid Pink spinel paired with 0.7 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-147",
    "sku": "GD26-147",
    "name": "Tanzanite and diamond hoop",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Tanzanite",
    "shape": "Round",
    "stonePcs": 2,
    "stoneCt": 0.21,
    "diamondCt": 1.33,
    "netG": 11.762,
    "grossG": 12.07,
    "story": "Crafted in 14k White gold, set with 1.21 carats of vivid round tanzanite paired with 1.33 carats of brilliant cut diamonds",
    "tone": "#3a5f9a"
  },
  {
    "id": "gd26-197-b",
    "sku": "GD26-197 B",
    "name": "Pink spinel and diamond motif earring",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "14k White and Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel",
    "shape": "Hexagon",
    "stonePcs": 8,
    "stoneCt": 2.93,
    "diamondCt": 1.68,
    "netG": 10.148,
    "grossG": 11.07,
    "story": "Crafted in 14k White gold, set with 2.93 carats of custom cut hexagon pink spinel paired with 1.68 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-198-c",
    "sku": "GD26-198 C",
    "name": "Tourmaline, rose quartz and diamond motif earring",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14t-W",
    "stone": "Tourmaline & Rose Quartz",
    "shape": "Triangle",
    "stonePcs": 12,
    "stoneCt": 3.28,
    "diamondCt": 0.93,
    "netG": 12.264,
    "grossG": 19.08,
    "story": "Crafted in 14k White gold, set with 3.28 carats of custom cut triangle tourmaline set in 29.87 carats of carved rose quartz paired with 0.93 carats of brilliant cut diamonds",
    "tone": "#2a7a5a"
  },
  {
    "id": "gd26-203",
    "sku": "GD26-203",
    "name": "Pink spinel, rose quartz and diamond motif earring",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Pink Spinel & Rose Quartz",
    "shape": "Pears",
    "stonePcs": 2,
    "stoneCt": 2.31,
    "diamondCt": 0.716,
    "netG": 11.341,
    "grossG": 14.99,
    "story": "Crafted in 18k White gold, set with 2.31 carats of pear shape pink spinel set in 15.22 carats of carved rose quartz paired with 0.71 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-218",
    "sku": "GD26-218",
    "name": "Pink spinel and diamond sleek dangler",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "14k Rose Gold",
    "metalCode": "G-14kt-R",
    "stone": "Pink Spinel",
    "shape": "Round",
    "stonePcs": 2,
    "stoneCt": 0.56,
    "diamondCt": 1.22,
    "netG": 8.444,
    "grossG": 8.8,
    "story": "Crafted in 14k Rose gold, set with 0.56 carats of vivid round pink spinel paired with 1.22 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-275-b",
    "sku": "GD26-275 B",
    "name": "Pink spinel and diamond motif stud",
    "collection": "Safar",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel",
    "shape": "Beads",
    "stonePcs": 2,
    "stoneCt": 3.54,
    "diamondCt": 1.73,
    "netG": 6.044,
    "grossG": 7.1,
    "story": "Crafted in 14k White gold, set with 3.54 carats of custom bead cut pink spinel paired with 1.73 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-141",
    "sku": "GD26-141",
    "name": "Morganite and diamond pendant",
    "collection": "Safar",
    "type": "Pendants",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Morganite",
    "shape": "Oval",
    "stonePcs": 1,
    "stoneCt": 2.04,
    "diamondCt": 0.45,
    "netG": 2.552,
    "grossG": 3.05,
    "story": "Crafted in 14k White gold, set with 2.04 carats of oval Morganite paired with 0.45 carats of brilliant cut diamonds",
    "tone": "#e8b4b8"
  },
  {
    "id": "gd26-197",
    "sku": "GD26-197",
    "name": "Pink spinel and diamond motif pendant",
    "collection": "Safar",
    "type": "Pendants",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel",
    "shape": "Hexagon",
    "stonePcs": 4,
    "stoneCt": 1.66,
    "diamondCt": 0.796,
    "netG": 5.349,
    "grossG": 5.84,
    "story": "Crafted in 14k White gold, set with 1.66 carats of custom cut hexagon pink spinel paired with 5.35 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-275-c",
    "sku": "GD26-275 C",
    "name": "Pink spinel and diamond motif pendant",
    "collection": "Safar",
    "type": "Pendants",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel",
    "shape": "Beads",
    "stonePcs": 1,
    "stoneCt": 1.78,
    "diamondCt": 1.37,
    "netG": 2.44,
    "grossG": 3.07,
    "story": "Crafted in 14k White gold, set with 1.78 carats of custom bead cut pink spinel paired with 2.44 carats of brilliant cut diamonds",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-1081",
    "sku": "GD25-1081",
    "name": "Mint garnet and diamond bloom pendant",
    "collection": "Bloom",
    "type": "Pendants",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Mint Garnet",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 1.55,
    "diamondCt": 0.45,
    "netG": 1.76,
    "grossG": 2.16,
    "story": "Crafted in 18k White gold, set with 1.55 carats of vivid mint green garnet paired with 0.45 carats of brilliant cut diamonds.",
    "tone": "#6a9e7a"
  },
  {
    "id": "gd25-1069",
    "sku": "GD25-1069",
    "name": "Mint garnet and diamond bloom ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Mint Garnet",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 2.47,
    "diamondCt": 1.1,
    "netG": 4.506,
    "grossG": 5.22,
    "story": "Crafted in 18k White gold, set with 2.47 carats of mint garnet paired with 1.1 carats of brilliant cut diamonds.",
    "tone": "#6a9e7a"
  },
  {
    "id": "gd25-1067",
    "sku": "GD25-1067",
    "name": "Mint garnet and diamond bloom earring",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Mint Garnet",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 4.31,
    "diamondCt": 1.12,
    "netG": 5.524,
    "grossG": 6.61,
    "story": "Crafted in 18k White gold, set with 4.31 carats of vivid mint green garnet paired with 1.12 carats of brilliant cut diamonds.",
    "tone": "#6a9e7a"
  },
  {
    "id": "gd25-994",
    "sku": "GD25-994",
    "name": "Mint garnet and diamond bloom bracelet",
    "collection": "Bloom",
    "type": "Bracelets",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Aquamarine",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 5.39,
    "diamondCt": 2.43,
    "netG": 16.826,
    "grossG": 18.39,
    "story": "Crafted in 18k White gold, set with 5.39 carats of vivid aquamarine paired with 2.43 carats of brilliant cut diamonds.",
    "tone": "#7eb8c9"
  },
  {
    "id": "gd25-1026",
    "sku": "GD25-1026",
    "name": "Aquamarine and diamond bloom ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Aquamarine",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 2.14,
    "diamondCt": 1.07,
    "netG": 4.558,
    "grossG": 5.2,
    "story": "Crafted in 18k White gold, set with 2.14 carats of radiant aquamarine paired with 1.07 carats of brilliant cut diamonds.",
    "tone": "#7eb8c9"
  },
  {
    "id": "gd25-1086",
    "sku": "GD25-1086",
    "name": "Aquamarine and diamond bloom earring",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Aquamarine",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 3.51,
    "diamondCt": 1.08,
    "netG": 5.402,
    "grossG": 6.32,
    "story": "Crafted in 18k White gold, set with 3.51 carats of radiant aquamarine paired with 1.08 carats of brilliant cut diamonds.",
    "tone": "#7eb8c9"
  },
  {
    "id": "gd25-1087",
    "sku": "GD25-1087",
    "name": "Aquamarine and diamond bloom pendant",
    "collection": "Bloom",
    "type": "Pendants",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Aquamarine",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 1.69,
    "diamondCt": 0.59,
    "netG": 2.484,
    "grossG": 2.94,
    "story": "Crafted in 18k White gold, set with 1.69 carats of radiant aquamarine paired with 0.59 carats of brilliant cut diamonds.",
    "tone": "#7eb8c9"
  },
  {
    "id": "gd25-875",
    "sku": "GD25-875",
    "name": "Tanzanite and diamond bloom bracelet",
    "collection": "Bloom",
    "type": "Bracelets",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Tanzanite",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 8.5,
    "diamondCt": 2.38,
    "netG": 20.514,
    "grossG": 22.69,
    "story": "Crafted in 18k White gold, set with 8.5 carats of intense blue tanzanite paired with 2.38 carats of brilliant cut diamonds.",
    "tone": "#3a5f9a"
  },
  {
    "id": "gd25-964",
    "sku": "GD25-964",
    "name": "Pink spinel and diamond petal bracelet",
    "collection": "Bloom",
    "type": "Bracelets",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel",
    "shape": "Mix",
    "stonePcs": null,
    "stoneCt": 1.56,
    "diamondCt": 1.67,
    "netG": 17.584,
    "grossG": 18.23,
    "story": "Crafted in 18k White gold, set with 1.56 carats of round and pear cut pink spinel paired with 1.67 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-1096",
    "sku": "GD25-1096",
    "name": "Pink spinel and diamond petal earring",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel",
    "shape": "Round",
    "stonePcs": null,
    "stoneCt": 0.74,
    "diamondCt": 0.66,
    "netG": 5.26,
    "grossG": 5.54,
    "story": "Crafted in 18k Rose gold, set with 0.74 carats of round pink spinel paired with 0.66 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-1095",
    "sku": "GD25-1095",
    "name": "Pink spinel and diamond petal ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel",
    "shape": "Round",
    "stonePcs": null,
    "stoneCt": 0.55,
    "diamondCt": 0.75,
    "netG": 4.05,
    "grossG": 4.31,
    "story": "Crafted in 18k Rose gold, set with 0.55 carats of round pink spinel paired with 0.75 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-1097",
    "sku": "GD25-1097",
    "name": "Pink spinel and diamond petal pendant",
    "collection": "Bloom",
    "type": "Pendants",
    "metal": "14k Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel",
    "shape": "Round",
    "stonePcs": null,
    "stoneCt": 0.64,
    "diamondCt": 0.46,
    "netG": 2.84,
    "grossG": 3.06,
    "story": "Crafted in 18k Rose gold, set with 0.64 carats of round pink spinel paired with 0.46 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-790",
    "sku": "GD26-790",
    "name": "Pink spinel and spessartite bloom long chain",
    "collection": "Bloom",
    "type": "Necklaces",
    "metal": "18k White Gold",
    "metalCode": "G-18kt",
    "stone": "Pink Spinel & Spessartite",
    "shape": "Mix",
    "stonePcs": null,
    "stoneCt": 4.77,
    "diamondCt": 1.03,
    "netG": 9.25,
    "grossG": 10.41,
    "story": "Crafted in 18k White gold, set with 0.94 carats of pink spinel paired with 3.83 carats spessartite and 1.03 of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-68",
    "sku": "GD26-68",
    "name": "Mint garnet and diamond garland necklace",
    "collection": "Bloom",
    "type": "Necklaces",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Mint Garnet",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 13.27,
    "diamondCt": 6.19,
    "netG": 38.868,
    "grossG": 42.76,
    "story": "Crafted in 14k White gold, set with 13.27 carats of pear mint garnet paired with 6.19 carats of brilliant cut diamonds.",
    "tone": "#6a9e7a"
  },
  {
    "id": "gd26-176",
    "sku": "GD26-176",
    "name": "Spessartite and diamond garland necklace",
    "collection": "Bloom",
    "type": "Necklaces",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Spessartite",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 17.28,
    "diamondCt": 5.88,
    "netG": 36.278,
    "grossG": 40.91,
    "story": "Crafted in 14k White gold, set with 17.28 carats of pear spessartite paired with 5.88 carats of brilliant cut diamonds.",
    "tone": "#d4783a"
  },
  {
    "id": "gd26-513",
    "sku": "GD26-513",
    "name": "Chalcedony and spessartite floral motif long chain",
    "collection": "Bloom",
    "type": "Necklaces",
    "metal": "18k White Gold",
    "metalCode": "G-18kt",
    "stone": "Spessartite & Chalcedony",
    "shape": "Pears Cabs",
    "stonePcs": null,
    "stoneCt": 6.89,
    "diamondCt": 2.16,
    "netG": 17.742,
    "grossG": 29.82,
    "story": "Crafted in 18k White gold, set with 6.89 carats of spessartite, 51.34 carats of chalcedony paired with 2.16 carats of round brilliant cut diamonds",
    "tone": "#d4783a"
  },
  {
    "id": "gd26-219",
    "sku": "GD26-219",
    "name": "Fancy tanzanite and diamond flora pendant",
    "collection": "Bloom",
    "type": "Pendants",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Tanzanite",
    "shape": "Fancy",
    "stonePcs": null,
    "stoneCt": 4.87,
    "diamondCt": 2.05,
    "netG": 6.686,
    "grossG": 8.07,
    "story": "Crafted in 14k White gold, set with 4.87 carats of intense blue fancy tanzanite paired with 2.05 carats of brilliant cut diamonds.",
    "tone": "#3a5f9a"
  },
  {
    "id": "gnk0923-27",
    "sku": "GNK0923-27",
    "name": "Pink spinel and diamond petal necklace",
    "collection": "Bloom",
    "type": "Necklaces",
    "metal": "18k White Gold",
    "metalCode": "Gold 18K",
    "stone": "Pink Spinel",
    "shape": "Sq-Cushion",
    "stonePcs": null,
    "stoneCt": 8.96,
    "diamondCt": 1.85,
    "netG": 17.977,
    "grossG": 20.14,
    "story": "Crafted in 18k Rose gold, set with 8.96 carats of round pink spinel paired with 1.85 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-1046",
    "sku": "GD25-1046",
    "name": "Heart in bloom rubellite and diamond dual finger ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Rubellite",
    "shape": "Heart Cabs",
    "stonePcs": null,
    "stoneCt": 3.44,
    "diamondCt": 2.121,
    "netG": 8.468,
    "grossG": 9.58,
    "story": "Crafted in 18k White gold, set with 3.44 carats of cabochon heart shaped rubellite paired with 2.12 carats of brilliant cut diamonds.",
    "tone": "#b8325a"
  },
  {
    "id": "gd25-124",
    "sku": "GD25-124",
    "name": "Pink spinel and diamond ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Pink Spinel",
    "shape": "Oval Cabs",
    "stonePcs": null,
    "stoneCt": 2.92,
    "diamondCt": 0.67,
    "netG": 7.506,
    "grossG": 8.224,
    "story": "Crafted in 18k White gold, set with 2.92 carats of cabochon oval shaped pink spinel paired with 0.67 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-1036",
    "sku": "GD25-1036",
    "name": "Morganite, pink spinel and diamond feather ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White and Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel & Morganite",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 3.39,
    "diamondCt": 1.36,
    "netG": 8.02,
    "grossG": 8.97,
    "story": "Crafted in 14k Rose gold, set with 1.81 carats of pear shaped pink spinel and 1.58 carats of morganite paired with 1.36 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-62",
    "sku": "GD26-62",
    "name": "Pink spinel and diamond rosette ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel",
    "shape": "Drops",
    "stonePcs": null,
    "stoneCt": 4.21,
    "diamondCt": 1.05,
    "netG": 4.888,
    "grossG": 5.94,
    "story": "Crafted in 14k White gold, set with 4.21 carats of drop shaped pink spinel paired with 1.05 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-71",
    "sku": "GD26-71",
    "name": "Mint garnet and diamond garland ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Mint Garnet",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 1.59,
    "diamondCt": 0.84,
    "netG": 4.344,
    "grossG": 4.83,
    "story": "Crafted in 14k White gold, set with 1.59 carats of pear shaped mint garnet paired with 0.84 carats of brilliant cut diamonds.",
    "tone": "#6a9e7a"
  },
  {
    "id": "gd26-139",
    "sku": "GD26-139",
    "name": "Heart in bloom tanzanite and diamond dual finger ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Tanzanite",
    "shape": "Heart",
    "stonePcs": null,
    "stoneCt": 4.02,
    "diamondCt": 2.05,
    "netG": 8.586,
    "grossG": 9.8,
    "story": "Crafted in 14k White gold, set with 4.02 carats of heart shaped tanzanite paired with 2.05 carats of brilliant cut diamonds.",
    "tone": "#3a5f9a"
  },
  {
    "id": "gd26-167",
    "sku": "GD26-167",
    "name": "Spessartite and diamond rosette ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Spessartite",
    "shape": "Drops",
    "stonePcs": null,
    "stoneCt": 3.9,
    "diamondCt": 0.94,
    "netG": 5.252,
    "grossG": 6.22,
    "story": "Crafted in 14k White gold, set with 3.9 carats of drop shape spessartite paired with 0.94 carats of brilliant cut diamonds.",
    "tone": "#d4783a"
  },
  {
    "id": "gd26-200",
    "sku": "GD26-200",
    "name": "Pink spinel, aquamarine and diamond bloom statement ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel & Aquamarine",
    "shape": "Mix",
    "stonePcs": null,
    "stoneCt": 3.81,
    "diamondCt": 1.38,
    "netG": 8.182,
    "grossG": 9.22,
    "story": "Crafted in 14k White gold, set with 2.46 carats of pink spinel and 1.35 carat of aquamarine paired with 1.38 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-201",
    "sku": "GD26-201",
    "name": "Spessartite, pink spinel and diamond bloom statement ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Spessartite & Pink Spinel",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 2.03,
    "diamondCt": 0.86,
    "netG": 5.562,
    "grossG": 6.14,
    "story": "Crafted in 14k White gold, set with 0.53 carats of pink spinel and 1.5 carat of spessartite paired with 0.86 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-766",
    "sku": "GD26-766",
    "name": "Aquamarine, pink spinel and diamond bloom statement ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Aquamarine & Pink Spinel",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 2.09,
    "diamondCt": 0.96,
    "netG": 6.49,
    "grossG": 7.1,
    "story": "Crafted in 18k White gold, set with 0.57 carats of pink spinel and 1.51 carat of aquamarine paired with 0.96 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-563",
    "sku": "GD26-563",
    "name": "Mint garnet and diamond bloom statement ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Mint Garnet",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 1.84,
    "diamondCt": 1.01,
    "netG": 6.01,
    "grossG": 6.58,
    "story": "Crafted in 18k White gold, set with 1.84 carats of mint garnet paired with 1.01 carats of brilliant cut diamonds.",
    "tone": "#6a9e7a"
  },
  {
    "id": "gd26-205",
    "sku": "GD26-205",
    "name": "Lavender tanzanite, tanzanite and diamond fern ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Tanzanite",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 7.23,
    "diamondCt": 0.56,
    "netG": 7.402,
    "grossG": 8.96,
    "story": "Crafted in 14k White gold, set with 7.23 carats of lavender and blue tanzanite paired with 0.56 carats of brilliant cut diamonds.",
    "tone": "#3a5f9a"
  },
  {
    "id": "gd26-206",
    "sku": "GD26-206",
    "name": "Spessartite, pink spinel and diamond fern ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel & Spessartite",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 8.75,
    "diamondCt": 0.58,
    "netG": 7.324,
    "grossG": 9.19,
    "story": "Crafted in 14k White gold, set with 1.04 carats of pink spinel and 7.71 carats of spessartite paired with 0.58 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-257",
    "sku": "GD26-257",
    "name": "Spessartite and diamond garland ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Spessartite",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 1.9,
    "diamondCt": 0.83,
    "netG": 4.594,
    "grossG": 5.14,
    "story": "Crafted in 14k White gold, set with 1.9 carats of spessartite paired with 0.83 carats of brilliant cut diamonds.",
    "tone": "#d4783a"
  },
  {
    "id": "gd26-566",
    "sku": "GD26-566",
    "name": "Heart in bloom crystal and tanzanite dual finger ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Tanzanite & Crystal",
    "shape": "Heart",
    "stonePcs": null,
    "stoneCt": 12.37,
    "diamondCt": 0.45,
    "netG": 4.216,
    "grossG": 6.78,
    "story": "Crafted in 18k White gold, set with 1.63 carats of heart shaped tanzanite, with 10.74 carats carved crystal paired with 0.45 carats brilliant cut diamonds.",
    "tone": "#3a5f9a"
  },
  {
    "id": "gd26-581",
    "sku": "GD26-581",
    "name": "Petal ring in Malaya garnet and diamond",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Malaya Garnet",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 9.76,
    "diamondCt": 1.905,
    "netG": 6.407,
    "grossG": 8.74,
    "story": "Crafted in 18k White gold, set with 9.76 carats of Malaya garnet paired with 1.9 carats brilliant cut diamonds.",
    "tone": "#c47858"
  },
  {
    "id": "gd26-583",
    "sku": "GD26-583",
    "name": "Spessartite and diamond bloom statement ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Spessartite",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 2.34,
    "diamondCt": 1.01,
    "netG": 6.15,
    "grossG": 6.82,
    "story": "Crafted in 18k White gold, set with 2.34 carats of spessartite paired with 1.01 carats of brilliant cut diamonds.",
    "tone": "#d4783a"
  },
  {
    "id": "gd25-1047",
    "sku": "GD25-1047",
    "name": "Heart in bloom rubellite and diamond ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "14k Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Rubellite",
    "shape": "Heart Cabs",
    "stonePcs": null,
    "stoneCt": 2.22,
    "diamondCt": 2.0,
    "netG": 4.716,
    "grossG": 5.56,
    "story": "Crafted in 18k White gold, set with 2.22 carats of cabochon heart shaped rubellite paired with 2 carats of brilliant cut diamonds.",
    "tone": "#b8325a"
  },
  {
    "id": "gd26-587",
    "sku": "GD26-587",
    "name": "Fancy tanzanite and diamond flora ring",
    "collection": "Bloom",
    "type": "Rings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Tanzanite",
    "shape": "Fancy",
    "stonePcs": null,
    "stoneCt": 4.09,
    "diamondCt": 1.87,
    "netG": 9.678,
    "grossG": 10.87,
    "story": "Crafted in 18k White gold, set with 4.09 carats of intense blue fancy tanzanite paired with 1.87 carats of brilliant cut diamonds.",
    "tone": "#3a5f9a"
  },
  {
    "id": "gd25-816",
    "sku": "GD25-816",
    "name": "In bloom pink spinel and diamond hoop",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Pink Spinel",
    "shape": "Oval Cabs",
    "stonePcs": null,
    "stoneCt": 5.33,
    "diamondCt": 5.15,
    "netG": 30.134,
    "grossG": 32.23,
    "story": "Crafted in 18k White gold, set with 5.33 carats of cabochon cut pink spinel paired with 5.15 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-435",
    "sku": "GD25-435",
    "name": "Heart in bloom pink rubellite earrings",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "18k Rose Gold",
    "metalCode": "G-18kt-W",
    "stone": "Rubellite",
    "shape": "Heart cab",
    "stonePcs": null,
    "stoneCt": 5.8,
    "diamondCt": 6.9,
    "netG": 21.16,
    "grossG": 23.7,
    "story": "Crafted in 18k White gold, set with 5.8 carats of cabochon heart shaped rubellite paired with 6.9 carats of brilliant cut diamonds.",
    "tone": "#b8325a"
  },
  {
    "id": "gd26-256",
    "sku": "GD26-256",
    "name": "Spessartite and diamond garland bracelet",
    "collection": "Bloom",
    "type": "Bracelets",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Spessartite",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 4.5,
    "diamondCt": 2.08,
    "netG": 18.414,
    "grossG": 19.73,
    "story": "Crafted in 14k White gold, set with 4.5 carats of spessartite paired with 2.08 carats of brilliant cut diamonds.",
    "tone": "#d4783a"
  },
  {
    "id": "gd26-69",
    "sku": "GD26-69",
    "name": "Mint garnet and diamond garland bracelet",
    "collection": "Bloom",
    "type": "Bracelets",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Mint Garnet",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 3.3,
    "diamondCt": 2.12,
    "netG": 18.086,
    "grossG": 19.17,
    "story": "Crafted in 14k White gold, set with 3.3 carats of mint garnet paired with 2.12 carats of brilliant cut diamonds.",
    "tone": "#6a9e7a"
  },
  {
    "id": "gd26-63",
    "sku": "GD26-63",
    "name": "Pink spinel and diamond rosette bracelet",
    "collection": "Bloom",
    "type": "Bracelets",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel",
    "shape": "Drops",
    "stonePcs": null,
    "stoneCt": 17.61,
    "diamondCt": 2.42,
    "netG": 17.774,
    "grossG": 21.78,
    "story": "Crafted in 14k White gold, set with 17.61 carats of vivid pink spinel drops paired with 2.42 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-aq-br",
    "sku": "GD26-AQ-BR",
    "name": "Aquamarine and diamond bloom bracelet",
    "collection": "Bloom",
    "type": "Bracelets",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Aquamarine",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 1.78,
    "diamondCt": 0.88,
    "netG": 4.528,
    "grossG": 5.06,
    "story": "Crafted in 18k White gold, set with 1.78 carats of vivid aquamarine paired with 0.88 carats of brilliant cut diamonds.",
    "tone": "#7eb8c9"
  },
  {
    "id": "gd26-762",
    "sku": "GD26-762",
    "name": "Pink spinel and diamond bloom bracelet",
    "collection": "Bloom",
    "type": "Bracelets",
    "metal": "18k White and Rose Gold",
    "metalCode": "G-18kt-WR",
    "stone": "Pink Spinel",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 2.15,
    "diamondCt": 0.97,
    "netG": 4.126,
    "grossG": 4.75,
    "story": "Crafted in 18k Rose gold, set with 2.15 carats of vivid pink spinel paired with 0.97 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-288",
    "sku": "GD25-288",
    "name": "Pink spinel and diamond bud earring",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Pink Spinel",
    "shape": "Oval Cabs",
    "stonePcs": null,
    "stoneCt": 7.8,
    "diamondCt": 1.55,
    "netG": 12.4,
    "grossG": 14.27,
    "story": "Crafted in 18k White gold, set with 7.8 carats of vivid pink spinel cabochon paired with 1.55 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd25-915-a",
    "sku": "GD25-915 A",
    "name": "Pink spinel and diamond bloom studs",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k Yellow Gold",
    "metalCode": "G-14kt-Y",
    "stone": "Pink Spinel",
    "shape": "Balls",
    "stonePcs": null,
    "stoneCt": 17.75,
    "diamondCt": 0.82,
    "netG": 15.926,
    "grossG": 19.64,
    "story": "Crafted in 18k Rose gold, set with 17.75 carats of vivid pink spinel drops paired with 0.82 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-60",
    "sku": "GD26-60",
    "name": "Pink spinel and diamond rosette studs",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Pink Spinel",
    "shape": "Drops",
    "stonePcs": null,
    "stoneCt": 9.8,
    "diamondCt": 3.22,
    "netG": 15.246,
    "grossG": 17.85,
    "story": "Crafted in 14k White gold, set with 9.8 carats of drop shape pink spinel paired with 3.22 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-70",
    "sku": "GD26-70",
    "name": "Mint garnet and diamond garland earring",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Mint Garnet",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 4.56,
    "diamondCt": 1.1,
    "netG": 11.868,
    "grossG": 13,
    "story": "Crafted in 14k White gold, set with 4.5 carats of mint garnet paired with 1.1 carats of brilliant cut diamonds.",
    "tone": "#6a9e7a"
  },
  {
    "id": "gd26-166",
    "sku": "GD26-166",
    "name": "Spessartite and diamond rosette studs",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Spessartite",
    "shape": "Drops",
    "stonePcs": null,
    "stoneCt": 25.65,
    "diamondCt": 3.39,
    "netG": 15.392,
    "grossG": 21.2,
    "story": "Crafted in 14k White gold, set with 25.65 carats of drop shape spessartite paired with 3.39 carats of brilliant cut diamonds.",
    "tone": "#d4783a"
  },
  {
    "id": "gd26-177",
    "sku": "GD26-177",
    "name": "Spessartite and diamond garland earring",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Spessartite",
    "shape": "Pears",
    "stonePcs": null,
    "stoneCt": 6.63,
    "diamondCt": 1.15,
    "netG": 10.704,
    "grossG": 12.26,
    "story": "Crafted in 14k White gold, set with 6.63 carats of spessartite paired with 1.1 carats of brilliant cut diamonds.",
    "tone": "#d4783a"
  },
  {
    "id": "gd26-210",
    "sku": "GD26-210",
    "name": "Pink spinel and diamond rosette studs rose",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k White and Rose Gold",
    "metalCode": "G-14kt-WR",
    "stone": "Pink Spinel",
    "shape": "Drops",
    "stonePcs": null,
    "stoneCt": 14.42,
    "diamondCt": 2.97,
    "netG": 15.342,
    "grossG": 18.82,
    "story": "Crafted in 14k Rose gold, set with 14.42 carats of drop shape pink spinel paired with 2.97 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  },
  {
    "id": "gd26-228-b",
    "sku": "GD26-228 B",
    "name": "Fancy tanzanite and diamond flora studs",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "14k White Gold",
    "metalCode": "G-14kt-W",
    "stone": "Tanzanite",
    "shape": "Fancy",
    "stonePcs": null,
    "stoneCt": 10.32,
    "diamondCt": 2.85,
    "netG": 14.406,
    "grossG": 17.04,
    "story": "Crafted in 14k White gold, set with 10.32 carats of intense blue fancy tanzanite paired with 2.85 carats of brilliant cut diamonds.",
    "tone": "#3a5f9a"
  },
  {
    "id": "gd26-785",
    "sku": "GD26-785",
    "name": "Spessartite, pink spinel and diamond garland earring",
    "collection": "Bloom",
    "type": "Earrings",
    "metal": "18k White Gold",
    "metalCode": "G-18kt-W",
    "stone": "Pink Spinel & Spessartite",
    "shape": "Mix",
    "stonePcs": null,
    "stoneCt": 4.21,
    "diamondCt": 0.97,
    "netG": 7.164,
    "grossG": 8.2,
    "story": "Crafted in 18k White gold, set with 0.5 carats of vivid pink spinel and 3.71 carats of spessartite paired with 0.97 carats of brilliant cut diamonds.",
    "tone": "#c45a7a"
  }
]
};
